// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptrjzamsuyssrmotqblc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0cmp6YW1zdXlzc3Jtb3RxYmxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjkzMjksImV4cCI6MjA2NTU0NTMyOX0.rhzpTgD5Id4Fsonj3kDQJjmSFQBlX8G36e-E_PqRG54";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);